import Footer from "@/components/Footer";
import HeaderPages from "@/components/HeaderPages";
import "../globals.css";

export const metadata = {
  title: "Traveling",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen ">
        <HeaderPages />
        <main className="flex-1 overflow-y-auto px-4 mx-auto container pt-20">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
